/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PNewRouteImport } from './routes/p/new'
import { Route as PPokemonIdIndexRouteImport } from './routes/p/$pokemonId/index'
import { Route as PPokemonIdEditRouteImport } from './routes/p/$pokemonId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PNewRoute = PNewRouteImport.update({
  id: '/p/new',
  path: '/p/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PPokemonIdIndexRoute = PPokemonIdIndexRouteImport.update({
  id: '/p/$pokemonId/',
  path: '/p/$pokemonId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPokemonIdEditRoute = PPokemonIdEditRouteImport.update({
  id: '/p/$pokemonId/edit',
  path: '/p/$pokemonId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/new': typeof PNewRoute
  '/p/$pokemonId/edit': typeof PPokemonIdEditRoute
  '/p/$pokemonId/': typeof PPokemonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/new': typeof PNewRoute
  '/p/$pokemonId/edit': typeof PPokemonIdEditRoute
  '/p/$pokemonId': typeof PPokemonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/new': typeof PNewRoute
  '/p/$pokemonId/edit': typeof PPokemonIdEditRoute
  '/p/$pokemonId/': typeof PPokemonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/new' | '/p/$pokemonId/edit' | '/p/$pokemonId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/new' | '/p/$pokemonId/edit' | '/p/$pokemonId'
  id: '__root__' | '/' | '/p/new' | '/p/$pokemonId/edit' | '/p/$pokemonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PNewRoute: typeof PNewRoute
  PPokemonIdEditRoute: typeof PPokemonIdEditRoute
  PPokemonIdIndexRoute: typeof PPokemonIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/new': {
      id: '/p/new'
      path: '/p/new'
      fullPath: '/p/new'
      preLoaderRoute: typeof PNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$pokemonId/': {
      id: '/p/$pokemonId/'
      path: '/p/$pokemonId'
      fullPath: '/p/$pokemonId/'
      preLoaderRoute: typeof PPokemonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$pokemonId/edit': {
      id: '/p/$pokemonId/edit'
      path: '/p/$pokemonId/edit'
      fullPath: '/p/$pokemonId/edit'
      preLoaderRoute: typeof PPokemonIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PNewRoute: PNewRoute,
  PPokemonIdEditRoute: PPokemonIdEditRoute,
  PPokemonIdIndexRoute: PPokemonIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
